### ISSUE TITLE
Error after losing connection with node

### ISSUE THREAD

**Issue by mate71pl** [mate-dev/mmrelaynode#8]
2023-12-06 11:53:28 +0000 INFO:Matrix:Syncing with server...
2023-12-06 11:53:28 +0000 INFO:Meshtastic:Relaying message from stef4nek to radio broadcast
2023-12-06 11:53:28 +0000 ERROR:Matrix:Error syncing with server: Data payload too big
2023-12-06 11:54:34 +0000 INFO:Matrix:Syncing with server...
2023-12-06 11:54:34 +0000 INFO:Meshtastic:Relaying message from PanBoczek to radio broadcast
2023-12-06 11:54:34 +0000 ERROR:Matrix:Error syncing with server: Data payload too big
2023-12-06 11:55:37 +0000 INFO:Matrix:Syncing with server...
Exception in thread Thread-629:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 1401, in run
    self.function(*self.args, **self.kwargs)
  File "/home/mesh/.local/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 632, in callback
    self._sendToRadio(p)
  File "/home/mesh/.local/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 690, in _sendToRadio
    self._sendToRadioImpl(toRadio)
  File "/home/mesh/.local/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 115, in _sendToRadioImpl
    self._writeBytes(header + b)
  File "/home/mesh/.local/lib/python3.11/site-packages/meshtastic/tcp_interface.py", line 72, in _writeBytes
    self.socket.send(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by mate71pl** [comment]
Temporary patch:
`docker logs mmrelaynode-app 2>&1 | tail -n 5 | grep -q -e 'BrokenPipeError' -e 'ERROR:Matrix' -e 'ERROR:Meshtastic' -e 'AttributeError' && docker restart mmrelaynode-app && echo "$(date '+%Y-%m-%d [%H:%M:%S] - Node restart!')" >> /home/mate/mmrelaynode/mmrelaynode.log`
Script run from cron every minute.

**Comment by mate71pl** [comment]
Until the bot script is fixed, the solution given must suffice. It is fast, low resource-intensive, and most importantly effective.
